### ISSUE TITLE
Change in tests "Altom" name in imports for C# package and update the build and the readme

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/EXAMPLES-CSharp-Android-AltTrahCat#2]
## Description
 
- Apply in tests the changes brought in the `feature-proxy` branch by https://github.com/alttester/AltTester-Unity-SDK/issues/984 for **the next release of the tester** (for pro 1.0 release)
- The example builds and the readme.md files will be updated, considering the new release (2.0.1)
- The driver will be updated to 2.0.1
- The dotnet will be updated to 7
## Additional info
- epic: https://github.com/alttester/AltTester-Unity-SDK/issues/1038
- the PR for this issue should be merged on the `main` branch only when we have the released tester for pro 1.0

**Comment by MihaiCuc98** [comment]
The testing session is done. Results:
![image](https://github.com/alttester/EXAMPLES-CSharp-Android-AltTrahCat/assets/113912901/5117e9f7-9f77-44f0-8536-fa587b72a70a)

Considering this information, ,I will move this ticket into `Done`.
