### ISSUE TITLE
Update example to use reverse port forwarding

### ISSUE THREAD

**Issue by iulianatodoran** [alttester/EXAMPLES-CSharp-Android-AltTrahCat#6]
## Description
 
Change in the setup the port forwarding with reverse port forwarding

## Additional info
- epic: https://github.com/alttester/AltTester-Unity-SDK/issues/1139
- the PR for this issue should be merged on the `main` branch only when we have the released tester for pro 1.0

**Comment by MihaiCuc98** [comment]
Tested in https://github.com/alttester/EXAMPLES-CSharp-Android-AltTrahCat/issues/2
